[package]
name = "fizzbuzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
simple-logging = "2.0.2"
ufmt = "0.2.0"


[profile.dev]
opt-level = 3
